### ISSUE TITLE
Error with angular 6 build prod mode

### ISSUE THREAD

**Issue by cristianstu** [maxisam/ngx-clipboard#135]
Getting this error compiling with `ng build --prod` on angular 6.0.3.
Everything working fine without `--prod` option. 

```
ERROR in ./node_modules/ngx-clipboard/src/clipboard.directive.ts
Module build failed: Error: node_modules/ngx-clipboard/src/clipboard.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/ngx-clipboard/src/clipboard.service.ts
Module build failed: Error: node_modules/ngx-clipboard/src/clipboard.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/ngx-clipboard/src/index.ts
Module build failed: Error: node_modules/ngx-clipboard/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by cristianstu** [comment]
Just realized that I was using an old version `8.1.4`
Everything fine with last version `11.1.0`
