### ISSUE TITLE
Angular Universal (Angular 8, 12.2.0) null window/document reference

### ISSUE THREAD

**Issue by coenmooij** [maxisam/ngx-clipboard#205]
When adding Angular Universal to my Angular 8 app, I'm getting this error when I refresh on a page where I've included the clipboard directive.

```
TypeError: Cannot read property 'document' of null
    at ClipboardService.destroy (/project/dist/server.js:161333:61)
    at ClipboardDirective.ngOnDestroy (/project/dist/server.js:161488:27)
    at callProviderLifecycles (project/dist/server.js:24510:18)
    at callElementProvidersLifecycles (/project/dist/server.js:24478:13)
    at callLifecycleHooksChildrenFirst (/project/dist/server.js:24468:29)
    at destroyView (/project/dist/server.js:32664:5)
    at callViewAction (/project/dist/server.js:32790:13)
    at execComponentViewsAction (/project/dist/server.js:32712:13)
    at destroyView (/project/dist/server.js:32663:5)
    at callViewAction (/project/dist/server.js:32790:13)
```
Referring to this line of code:
https://github.com/maxisam/ngx-clipboard/blob/c725ebbd937ae9fa451c17f863908ceaf699afcd/projects/ngx-clipboard/src/lib/ngx-clipboard.service.ts#L92

Is there a reason it's not using `this.document` instead of `this.window.document`?

The same happens one more time a little bit earlier in the file:
https://github.com/maxisam/ngx-clipboard/blob/c725ebbd937ae9fa451c17f863908ceaf699afcd/projects/ngx-clipboard/src/lib/ngx-clipboard.service.ts#L67

**Comment by maxisam** [comment]
I think you are correct. We should use this.document instead. Do you want to create a pull request?

**Comment by coenmooij** [comment]
will do @maxisam 👍

**Comment by maxisam** [comment]
please try 12.2.1-beta.2

**Comment by coenmooij** [comment]
Didn't have a lot of time past days, but I just checked it, and glad to report it solved the issue.
Thanks for the fast help! @maxisam

**Comment by maxisam** [comment]
@coenmooij  no problem. Thank you for making a pull request.
