### ISSUE TITLE
Problem with ngx-window-token dependency

### ISSUE THREAD

**Issue by vegarda** [maxisam/ngx-clipboard#282]
angular@10

ngx-clipboard@14.0.1

```
ERROR in ./node_modules/ngx-window-token/fesm2015/ngx-window-token.mjs 3:19-33
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)
@ ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js
```

**Comment by AliKholmatov** [comment]
@maxisam Could you help with it? the same issue

**Comment by KrakenTyio** [comment]
same issue on node 16 and angular 11
```
Warning: /app/node_modules/ngx-window-token/fesm2015/ngx-window-token.mjs depends on '@angular/core'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



Error: ./node_modules/ngx-window-token/fesm2015/ngx-window-token.mjs 2:19-33
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/app/node_modules/webpack/lib/Compilation.js:1463:22)
    at /app/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at eval (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:57:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 @ ./node_modules/ngx-clipboard/__ivy_ngcc__/fesm2015/ngx-clipboard.js
 @ ./src/app/settings/webbooking/wb-weblinks/wb-weblinks.component.ts
 @ ./src/app/settings/settings.module.ts
 @ ./src/lazy/finance.setup.lazy.ts
 @ ./src/app/finance/invoice-section/invoice-section-abstract.directive.ts
 @ ./src/app/finance/invoice-section/invoice-treatment-overview/invoice-treatment-overview.component.ts
 @ ./src/app/finance/treatments/treatments-actions-panel/treatments-actions-panel.component.ts
 @ ./src/app/finance/treatments/treatments-actions-panel/treatments-actions-panel.module.ts
 @ ./src/lazy/treatments.lazy.ts
 @ ./src/lib/invoice/invoice.actions.service.ts
 @ ./src/lib/invoice/invoice.actions.module.ts
 @ ./src/base.module.ts
 @ ./src/app.module.ts
 @ ./src/app.ts
 @ multi ./src/app.ts
```

**Comment by yann-mangin** [comment]
I can see that a v15.0.0 has been published 30 minutes ago. I tried that version but the error persists with docker build on Jenkins.
The error showing is now the following:
`ERROR in node_modules/ngx-clipboard/lib/ngx-clipboard.service.d.ts:60:21 - error TS2694: Namespace '"/mnt/jenkins/workspace/PRM-6205-resolve-mt-dependencies/ng-tb-journal/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.`

**Comment by KrakenTyio** [comment]
for now quick fix to add `ngx-window-token` as sibling deps in package.json
```
"ngx-clipboard": "~14.0.1",
"ngx-window-token": "~5.0.0",
```

**Comment by maxisam** [comment]
this issue has been discussed at https://github.com/maxisam/ngx-window-token/issues/46

In short, @KrakenTyio 's workaround is good. I will publish another 14 to lock the version today.

**Comment by maxisam** [comment]
hi all, please use 14.0.2 thx

**Comment by maxisam** [comment]
@vegarda is it good to close this?

**Comment by surajpoddar16** [comment]
@maxisam Can we do this to support Angular 9 as well?

**Comment by alenandry** [comment]
node_modules/ngx-window-token/fesm2015/ngx-window-token.mjs
open this file
```ts
import {InjectionToken} from '@angular/core';
const WINDOW = new InjectionToken('WindowToken', typeof window !== 'undefined' && window.document
    ? { providedIn: 'root', factory: () => window }
    : { providedIn: 'root', factory: () => undefined });
export { WINDOW };
```
replace with this code
```ts
import InjectionToken from '@angular/core';
const WINDOW = new InjectionToken('WindowToken', typeof window !== 'undefined' && window.document
    ? { providedIn: 'root', factory: () => window }
    : { providedIn: 'root', factory: () => undefined });
export { WINDOW };
```
