### ISSUE TITLE
Angular2 - Issue wih clipboard after i18n integration

### ISSUE THREAD

**Issue by PrashansaM-optimus** [maxisam/ngx-clipboard#62]
On running npm run i18n command, getting the below error:
Error: ENOENT: no such file or directory, open 'dist\out-tsc\node_modules\ngx-clipboard\src\window.service.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at MetadataWriterHost.writeMetadata (\node_modules\@angular\tsc-wrapped\src\compiler_host.js:164:22)
    at MetadataWriterHost.writeFile (\node_modules\@angular\tsc-wrapped\src\compiler_host.js:143:19)
    at Object.writeFile \node_modules\typescript\lib\typescript.js:45369:132)
    at Object.writeFile (\node_modules\typescript\lib\typescript.js:7602:14)
    at writeEmittedFiles (\node_modules\typescript\lib\typescript.js:37859:20)
    at doEmit (\node_modules\typescript\lib\typescript.js:37719:17)
    at emitFile (\node_modules\typescript\lib\typescript.js:44665:21)
Extraction failed

Additional Information:
    "angular/compiler-cli": "^2.3.1",
    "types/jasmine": "2.5.38",
    "types/node": "^6.0.42",
    "types/lodash": "4.14.50",
    "angular-cli": "1.0.0-beta.26",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "typescript": "~2.0.3",
    "ngx-clipboard": "6.0.6"

"scripts": {
"i18n": "ng-xi18n -p src/tsconfig.json"
}

**Comment by maxisam** [comment]
can you try 7.0.6?

**Comment by PrashansaM-optimus** [comment]
Thanks for the quick response. 7.0.6 works. 

Thanks for the library. Its Easy to use.
