### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by iTwangcj** [maxisam/ngx-clipboard#72]
> angular-mock@0.0.0 prestart /Users/wangchengjun/www/yooli/mock/angular-mock
> ng build --env=dev && ngc

Date: 2017-09-19T05:20:41.322Z                                                          
Hash: fb16296141ea66072b65
Time: 18711ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 360 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 209 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 118 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.22 MB [initial] [rendered]

> angular-mock@0.0.0 start /Users/wangchengjun/www/yooli/mock/angular-mock
> ts-node backend/server.ts | bunyan

/Users/wangchengjun/www/yooli/mock/angular-mock/node_modules/ngx-clipboard/dist/node_modules/ngx-window-token/index.js:1
(function (exports, require, module, __filename, __dirname) { export { WindowTokenModule, WINDOW } from './src/index';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ClipboardService.ClipboardService.window.document (/Users/wangchengjun/www/yooli/mock/angular-mock/node_modules/ngx-clipboard/dist/bundles/ngxClipboard.umd.min.js:1:160)
    at Object.<anonymous> (/Users/wangchengjun/www/yooli/mock/angular-mock/node_modules/ngx-clipboard/dist/bundles/ngxClipboard.umd.min.js:1:534)

**Comment by maxisam** [comment]
please try 8.1.1

**Comment by Gajendrasinh** [comment]
I am also get same issue, i have try v8.1.1 then i got bellow error can you help me


module.js:540
    throw err;
    ^

Error: Cannot find module 'ngx-clipboard/src/clipboard.directive'
    at Function.Module._resolveFilename (module.js:538:15) [<root>]
    at Function.Module._load (module.js:468:25) [<root>]
    at Module.require (module.js:587:17) [<root>]
    at require (internal/module.js:11:18) [<root>]
    at Object.<anonymous> (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:791947) [<root>]
    at __webpack_require__ (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:285) [<root>]
    at Object.defineProperty.value (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:286444) [<root>]
    at __webpack_require__ (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:285) [<root>]
    at Object.<anonymous> (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:582016) [<root>]
    at __webpack_require__ (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:285) [<root>]
    at Object.<anonymous> (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:792945) [<root>]
    at Object.<anonymous> (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:793735) [<root>]
    at __webpack_require__ (/Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:285) [<root>]
    at /Volumes/DATA/Projects/Tropitoken-AngularJS/front/dist/server.js:1:1016 [<root>]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tropiToken@0.0.0 startDev: `ng build --prod --env=dev --aot && gulp && ngc && webpack && PORT=5025 node dist/server.js `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tropiToken@0.0.0 startDev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
