### ISSUE TITLE
Ionic Production Build Fails

### ISSUE THREAD

**Issue by thandaanda** [maxisam/ngx-clipboard#75]
Hi,

While building for production, build fails with this error,

`Error: ./node_modules/ngx-window-token/src/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 43:0-50
 @ ./src/app/main.ts,./node_modules/ngx-clipboard/src/clipboard.service.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 44:0-59
 @ ./src/app/main.ts,./node_modules/ngx-clipboard/src/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 98:0-47
 @ ./src/app/main.ts,./node_modules/ngx-clipboard/src/clipboard.directive.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.component.ngfactory.js 35:0-61
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at new BuildError (/home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /home/keyur/Documents/Git/am-mobile-2/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by maxisam** [comment]
My guess is ionic doesn't have window object?

**Comment by thandaanda** [comment]
Hi @maxisam ,
It runs fine when development is on.
When I run production builds it fails or rather during webpack optimazation.

**Comment by maxisam** [comment]
please try v8.1.1

**Comment by conquor** [comment]
hi @maxisam, 
I meet the same issue, used v8.1.1

**Comment by Malkiat-Singh** [comment]
@maxisam  same issue with v8.1.1 
will try v5.0.1

**Comment by anshuman-singh-93** [comment]
in your app.module.ts
instead of 
`import {ClipboardModule} from "ngx-clipboard";
`
use
`import {ClipboardModule} from "ngx-clipboard/dist/src";
`

**Comment by jasonz1987** [comment]
@anshuman-singh-93  
it's works,tks!

**Comment by thandaanda** [comment]
Thanks @jasonz1987 . Closing for now.

**Comment by Malkiat-Singh** [comment]
@anshuman-singh-93  
import {ClipboardModule} from "ngx-clipboard/dist/src";
if you use this and build with --prod this is not bulding 
there is error at build time
