### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module ~/node_modules/ngx-clipboard/dist/src/clipboard.service.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by fuchao2012** [maxisam/ngx-clipboard#93]
as describe in title.

```
ERROR in Error: Metadata version mismatch for module /Volumes/store/workspace/ne/support/documents-web/node_modules/ngx-clipboard/dist/src/clipboard.service.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler/bundles/compiler.umd.js:25385:14)
    at /Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (native)
    at extractProgramSymbols (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler/bundles/compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler/bundles/compiler.umd.js:23796:47)
    at CodeGenerator.codegen (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Volumes/store/workspace/ne/support/documents-web/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/Volumes/store/workspace/ne/support/documents-web/node_modules/@ngtools/webpack/src/plugin.js:430:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by igormilla** [comment]
It seems that the author transitioned library from angular 4 to angular 5 when upgrading this library from 8.1.1 to 8.1.2, and this made it incompatible with angular 4 applications. If you don't want to upgrade your code to angular 5, just stick with 8.1.1 version of this package

**Comment by maxisam** [comment]
please try 8.1.3 thanks!
